import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import dns from 'dns';

try {
  dns.setServers(['8.8.8.8', '8.8.4.4', '1.1.1.1']);
} catch (e) {}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, '../.env') });

import User from '../models/userModel.js';
import Category from '../models/categoryModel.js';
import Market from '../models/marketModel.js';
import FarmerProfile from '../models/farmerProfileModel.js';
import Product from '../models/productModel.js';
import Review from '../models/reviewModel.js';
import Order from '../models/orderModel.js';
import Banner from '../models/bannerModel.js';

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.Database;
    if (!mongoUri) {
      throw new Error('Database URI missing in .env');
    }

    await mongoose.connect(mongoUri);
    console.log('🌱 Connected to MongoDB for seeding...');

    // ── 1. SEED CATEGORIES (12 Categories) ──
    const categoriesData = [
      {
        name: 'Fresh Vegetables',
        slug: 'fresh-vegetables',
        description: 'Farm-fresh organic leafy greens, root vegetables, gourds, and vine-ripened produce.',
        image: { url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: true,
        position: 1,
      },
      {
        name: 'Organic Fruits',
        slug: 'organic-fruits',
        description: 'Seasonal orchard fresh fruits, sweet berries, citrus, mangoes, and mountain apples.',
        image: { url: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: true,
        position: 2,
      },
      {
        name: 'Dairy & Farm Eggs',
        slug: 'dairy-eggs',
        description: 'Pasture-raised organic eggs, pure grass-fed milk, farm butter, and artisanal cheese.',
        image: { url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: true,
        position: 3,
      },
      {
        name: 'Artisan Honey & Jams',
        slug: 'honey-jams',
        description: 'Pure raw wildflower honey, cold-extracted sidr honey, and natural handcrafted fruit jams.',
        image: { url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: true,
        position: 4,
      },
      {
        name: 'Bakery & Grains',
        slug: 'bakery-grains',
        description: 'Naturally fermented sourdough breads, whole grain flours, and stone-ground cereals.',
        image: { url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: true,
        position: 5,
      },
      {
        name: 'Fresh Herbs & Spices',
        slug: 'herbs-spices',
        description: 'Aromatic culinary herbs, organic dried spices, mint, basil, and natural herbal seasonings.',
        image: { url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: true,
        position: 6,
      },
      {
        name: 'Cold-Pressed Juices',
        slug: 'cold-pressed-juices',
        description: 'Raw unpasteurized cold-pressed fruit juices, green elixirs, and kombucha blends.',
        image: { url: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: false,
        position: 7,
      },
      {
        name: 'Farm Pantry & Preserves',
        slug: 'pantry-preserves',
        description: 'Homemade organic pickles, sun-dried tomatoes, olive oils, and cold-pressed mustard oils.',
        image: { url: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: false,
        position: 8,
      },
      {
        name: 'Gourmet Mushrooms',
        slug: 'gourmet-mushrooms',
        description: 'Fresh organic oyster, shiitake, lion\'s mane, and button mushrooms grown in eco-farms.',
        image: { url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: false,
        position: 9,
      },
      {
        name: 'Microgreens & Sprouts',
        slug: 'microgreens-sprouts',
        description: 'Nutrient-dense live sunflower sprouts, radish microgreens, and pea shoots.',
        image: { url: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: false,
        position: 10,
      },
      {
        name: 'Raw Nuts & Seeds',
        slug: 'nuts-seeds',
        description: 'Sun-dried raw almonds, walnuts, pumpkin seeds, and organic chia seeds direct from valleys.',
        image: { url: 'https://images.unsplash.com/photo-1508746829417-e6f548d8d6ed?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: false,
        position: 11,
      },
      {
        name: 'Artisan Cheeses',
        slug: 'artisan-cheeses',
        description: 'Handcrafted goat feta, fresh paneer, mozzarella, and aged artisanal gouda.',
        image: { url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&auto=format&fit=crop&q=80' },
        isActive: true,
        isFeatured: false,
        position: 12,
      },
    ];

    const savedCategories = [];
    for (const cat of categoriesData) {
      let existing = await Category.findOne({ $or: [{ slug: cat.slug }, { name: cat.name }] });
      if (!existing) {
        existing = await Category.create(cat);
      } else {
        Object.assign(existing, cat);
        await existing.save();
      }
      savedCategories.push(existing);
    }
    console.log(`✅ Seeded ${savedCategories.length} Categories.`);

    // ── 2. SEED MARKETS (10 Markets) ──
    const marketsData = [
      {
        name: 'Clifton Organic Farmers Market',
        slug: 'clifton-organic-farmers-market',
        description: 'Premier seaside weekend organic market featuring fresh coastal harvest, dairy, and artisanal products.',
        image: { url: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Block 4, Marine Promenade, Clifton',
          city: 'Karachi',
          coordinates: { lat: 24.8138, lng: 67.0299 },
        },
        marketDays: ['Saturday', 'Sunday'],
        openTime: '08:00 AM',
        closeTime: '02:00 PM',
        pickupStartTime: '08:30 AM',
        pickupEndTime: '01:30 PM',
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'DHA Botanical Green Bazaar',
        slug: 'dha-botanical-green-bazaar',
        description: 'Lush parkside market bringing organic growers directly to neighborhood families.',
        image: { url: 'https://images.unsplash.com/photo-1533900298318-6b8da08a523e?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Phase 6 Botanical Gardens, Khayaban-e-Seher',
          city: 'Karachi',
          coordinates: { lat: 24.8021, lng: 67.0543 },
        },
        marketDays: ['Friday', 'Saturday'],
        openTime: '09:00 AM',
        closeTime: '03:00 PM',
        pickupStartTime: '09:30 AM',
        pickupEndTime: '02:30 PM',
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Gulshan Community Agri Hub',
        slug: 'gulshan-community-agri-hub',
        description: 'Central Karachi pickup hub with organic vegetable crates, fresh farm milk, and raw honey.',
        image: { url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Near Safari Park Ground, Block 11, Gulshan-e-Iqbal',
          city: 'Karachi',
          coordinates: { lat: 24.9180, lng: 67.1147 },
        },
        marketDays: ['Saturday', 'Sunday'],
        openTime: '07:30 AM',
        closeTime: '01:00 PM',
        pickupStartTime: '08:00 AM',
        pickupEndTime: '12:30 PM',
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'F-7 Organic Saturday Ground',
        slug: 'f7-organic-saturday-ground',
        description: 'Capital city\'s favorite morning farmers fair with heirloom fruits, microgreens, and mountain walnuts.',
        image: { url: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Jinnah Super Green Park, Sector F-7/2',
          city: 'Islamabad',
          coordinates: { lat: 33.7215, lng: 73.0566 },
        },
        marketDays: ['Saturday', 'Sunday'],
        openTime: '08:00 AM',
        closeTime: '02:00 PM',
        pickupStartTime: '08:30 AM',
        pickupEndTime: '01:30 PM',
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Kohsar Sunrise Farmers Market',
        slug: 'kohsar-sunrise-farmers-market',
        description: 'Artisanal organic marketplace with farm cheese, fresh sourdough loaves, and herb bundles.',
        image: { url: 'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Kohsar Market Plaza, Sector F-6/3',
          city: 'Islamabad',
          coordinates: { lat: 33.7311, lng: 73.0722 },
        },
        marketDays: ['Friday', 'Sunday'],
        openTime: '08:30 AM',
        closeTime: '01:30 PM',
        pickupStartTime: '09:00 AM',
        pickupEndTime: '01:00 PM',
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Model Town Heritage Produce Market',
        slug: 'model-town-heritage-produce-market',
        description: 'Historic Lahore circular park market with fresh dairy, country chicken eggs, and organic citrus.',
        image: { url: 'https://images.unsplash.com/photo-1526399232581-2ab5608b6336?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Model Town Central Park, Block C',
          city: 'Lahore',
          coordinates: { lat: 31.4883, lng: 74.3213 },
        },
        marketDays: ['Saturday', 'Sunday'],
        openTime: '07:00 AM',
        closeTime: '01:00 PM',
        pickupStartTime: '07:30 AM',
        pickupEndTime: '12:30 PM',
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Gulberg Green Organic Square',
        slug: 'gulberg-green-organic-square',
        description: 'Vibrant urban farmers gathering with certified pesticide-free vegetables and raw cold-pressed oils.',
        image: { url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Main Boulevard, Gulberg III',
          city: 'Lahore',
          coordinates: { lat: 31.5204, lng: 74.3587 },
        },
        marketDays: ['Friday', 'Saturday'],
        openTime: '08:00 AM',
        closeTime: '02:00 PM',
        pickupStartTime: '08:30 AM',
        pickupEndTime: '01:30 PM',
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'DHA Raya Farm Gate Market',
        slug: 'dha-raya-farm-gate-market',
        description: 'Weekend farm gate station featuring exotic mushrooms, fresh strawberries, and gourmet herbs.',
        image: { url: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Fairways Commercial, Phase 6 DHA',
          city: 'Lahore',
          coordinates: { lat: 31.4678, lng: 74.4321 },
        },
        marketDays: ['Saturday', 'Sunday'],
        openTime: '09:00 AM',
        closeTime: '03:00 PM',
        pickupStartTime: '09:30 AM',
        pickupEndTime: '02:30 PM',
        isActive: true,
        isFeatured: true,
      },
      {
        name: 'Cantt Eco Farmers Station',
        slug: 'cantt-eco-farmers-station',
        description: 'Community pickup point connecting Rawalpindi residents with organic Potohar plateau farmers.',
        image: { url: 'https://images.unsplash.com/photo-1506484381205-f7945653044d?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'Ayub National Park Gate 2, Rawalpindi Cantt',
          city: 'Rawalpindi',
          coordinates: { lat: 33.5651, lng: 73.0825 },
        },
        marketDays: ['Sunday', 'Wednesday'],
        openTime: '08:00 AM',
        closeTime: '01:30 PM',
        pickupStartTime: '08:30 AM',
        pickupEndTime: '01:00 PM',
        isActive: true,
        isFeatured: false,
      },
      {
        name: 'Faisalabad Agri University Market',
        slug: 'faisalabad-agri-university-market',
        description: 'University research supported organic farmers fair offering certified non-GMO seasonal crops.',
        image: { url: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop&q=80' },
        location: {
          address: 'University Road, Agricultural University Ground',
          city: 'Faisalabad',
          coordinates: { lat: 31.4278, lng: 73.0758 },
        },
        marketDays: ['Saturday', 'Sunday'],
        openTime: '07:30 AM',
        closeTime: '01:00 PM',
        pickupStartTime: '08:00 AM',
        pickupEndTime: '12:30 PM',
        isActive: true,
        isFeatured: false,
      },
    ];

    const savedMarkets = [];
    for (const m of marketsData) {
      let existing = await Market.findOne({ $or: [{ slug: m.slug }, { name: m.name }] });
      if (!existing) {
        existing = await Market.create(m);
      } else {
        Object.assign(existing, m);
        await existing.save();
      }
      savedMarkets.push(existing);
    }
    console.log(`✅ Seeded ${savedMarkets.length} Markets.`);

    // ── 3. SEED FARMER USERS & PROFILES (10 Farmers) ──
    const farmersSeed = [
      {
        user: {
          name: 'Tariq Mehmood',
          email: 'tariq.farmer@marketlink.org',
          phone: '+92 301 2345678',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Green Valley Organic Homestead',
          slug: 'green-valley-organic-homestead',
          contactPerson: 'Tariq Mehmood',
          phone: '+92 301 2345678',
          email: 'tariq.farmer@marketlink.org',
          address: 'Rural Hub, Malir Farms',
          stallNumber: 'Stall #04',
          description: '3rd generation family farm specializing in 100% pesticide-free heritage tomatoes, crunchy greens, and seasonal organic vegetables.',
          specialties: ['Heirloom Tomatoes', 'Organic Spinach', 'Persian Cucumbers', 'Bell Peppers'],
          certifications: ['Certified Organic', 'Pesticide-Free', 'Non-GMO'],
          operatingDays: ['Saturday', 'Sunday'],
          rating: 4.9,
          reviewCount: 28,
          coverImage: { url: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 0,
        },
      },
      {
        user: {
          name: 'Asad Ullah Khan',
          email: 'asad.orchard@marketlink.org',
          phone: '+92 302 3456789',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Sunburst Citrus & Apple Orchards',
          slug: 'sunburst-citrus-apple-orchards',
          contactPerson: 'Asad Ullah Khan',
          phone: '+92 302 3456789',
          email: 'asad.orchard@marketlink.org',
          address: 'Swat Valley Foothills',
          stallNumber: 'Stall #12',
          description: 'High-altitude mountain orchards growing sweet crisp apples, ruby pomegranates, and sun-ripened citrus fruits.',
          specialties: ['Mountain Apples', 'Organic Pomegranates', 'Sweet Citrus', 'Fresh Strawberries'],
          certifications: ['Organic Valley Certified', 'Zero Chemical Spray'],
          operatingDays: ['Saturday', 'Sunday'],
          rating: 4.8,
          reviewCount: 34,
          coverImage: { url: 'https://images.unsplash.com/photo-1526399232581-2ab5608b6336?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 3,
        },
      },
      {
        user: {
          name: 'Zainab Bibi',
          email: 'zainab.dairy@marketlink.org',
          phone: '+92 303 4567890',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Happy Hen Pasture & Dairy Farm',
          slug: 'happy-hen-pasture-dairy-farm',
          contactPerson: 'Zainab Bibi',
          phone: '+92 303 4567890',
          email: 'zainab.dairy@marketlink.org',
          address: 'Chuharkana Pastoral Grounds',
          stallNumber: 'Stall #08',
          description: 'Ethical pastured poultry and grass-fed dairy farm providing daily morning farm fresh eggs, butter, and raw whole milk.',
          specialties: ['Pastured Eggs', 'Grass-Fed Milk', 'Artisan Butter', 'Fresh Paneer'],
          certifications: ['Humanely Raised', 'Pasture-Fed', 'Hormone-Free'],
          operatingDays: ['Friday', 'Saturday', 'Sunday'],
          rating: 5.0,
          reviewCount: 42,
          coverImage: { url: 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 5,
        },
      },
      {
        user: {
          name: 'Master Farooq',
          email: 'farooq.honey@marketlink.org',
          phone: '+92 304 5678901',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Indus Bee Raw Wildflower Apiary',
          slug: 'indus-bee-raw-wildflower-apiary',
          contactPerson: 'Master Farooq',
          phone: '+92 304 5678901',
          email: 'farooq.honey@marketlink.org',
          address: 'Margalla Foothills Apiaries',
          stallNumber: 'Stall #18',
          description: 'Unprocessed, cold-extracted raw sidr, berry, and wildflower honeys rich in enzymes, propolis, and natural bee pollen.',
          specialties: ['Raw Sidr Honey', 'Wildflower Blossom Honey', 'Proolis Tinctures', 'Beeswax Candles'],
          certifications: ['100% Raw Unfiltered', 'Pure Artisan'],
          operatingDays: ['Saturday', 'Sunday'],
          rating: 4.9,
          reviewCount: 39,
          coverImage: { url: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 4,
        },
      },
      {
        user: {
          name: 'Fatima Zahra',
          email: 'fatima.herbs@marketlink.org',
          phone: '+92 305 6789012',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Highland Herb & Botanical Sanctuary',
          slug: 'highland-herb-botanical-sanctuary',
          contactPerson: 'Fatima Zahra',
          phone: '+92 305 6789012',
          email: 'fatima.herbs@marketlink.org',
          address: 'Murree Agro-Botanical Patch',
          stallNumber: 'Stall #06',
          description: 'Cultivating medicinal herbs, fragrant culinary mint, Italian sweet basil, rosemary, and calming chamomile.',
          specialties: ['Sweet Italian Basil', 'Mountain Mint', 'Fresh Rosemary', 'Dried Oregano'],
          certifications: ['Organically Grown', 'Zero Chemical'],
          operatingDays: ['Friday', 'Saturday'],
          rating: 4.9,
          reviewCount: 22,
          coverImage: { url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 1,
        },
      },
      {
        user: {
          name: 'Dr. Kamran Shah',
          email: 'kamran.fungi@marketlink.org',
          phone: '+92 306 7890123',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Forest Fungi & Gourmet Mushrooms',
          slug: 'forest-fungi-gourmet-mushrooms',
          contactPerson: 'Dr. Kamran Shah',
          phone: '+92 306 7890123',
          email: 'kamran.fungi@marketlink.org',
          address: 'Eco Climate Chamber, Sector I-9',
          stallNumber: 'Stall #21',
          description: 'Sustainable mycological farm producing fresh gourmet oyster, king trumpet, and lion’s mane mushrooms.',
          specialties: ['Grey Oyster Mushrooms', 'Shiitake Caps', 'Lion\'s Mane', 'Mushroom Powder'],
          certifications: ['Lab Certified Organic', 'Clean Room Cultivated'],
          operatingDays: ['Saturday', 'Sunday'],
          rating: 4.8,
          reviewCount: 19,
          coverImage: { url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 3,
        },
      },
      {
        user: {
          name: 'Ayesha Siddiqui',
          email: 'ayesha.sprouts@marketlink.org',
          phone: '+92 307 8901234',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Urban Microgreens & Live Sprouts',
          slug: 'urban-microgreens-live-sprouts',
          contactPerson: 'Ayesha Siddiqui',
          phone: '+92 307 8901234',
          email: 'ayesha.sprouts@marketlink.org',
          address: 'Vertical Hydro-Farm, Clifton',
          stallNumber: 'Stall #02',
          description: 'Live microgreens packed with up to 40x more nutrients than mature greens. Harvested on morning of market.',
          specialties: ['Broccoli Microgreens', 'Sunflower Sprouts', 'Radish Shoots', 'Wheatgrass'],
          certifications: ['Hydro-Organic', 'Non-GMO Seeds'],
          operatingDays: ['Saturday', 'Sunday'],
          rating: 5.0,
          reviewCount: 25,
          coverImage: { url: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 0,
        },
      },
      {
        user: {
          name: 'Bilal Ahmed',
          email: 'bilal.juice@marketlink.org',
          phone: '+92 308 9012345',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Pure Press Cold Juices & Elixirs',
          slug: 'pure-press-cold-juices-elixirs',
          contactPerson: 'Bilal Ahmed',
          phone: '+92 308 9012345',
          email: 'bilal.juice@marketlink.org',
          address: 'Agri Estate, Bedian Road',
          stallNumber: 'Stall #15',
          description: '100% pure cold-pressed organic juices with zero added sugars, preservatives, or artificial additives.',
          specialties: ['Carrot-Orange Glow', 'Green Detox Elixir', 'Beet-Apple Energy', 'Ginger-Turmeric Shots'],
          certifications: ['Raw & Unpasteurized', 'Cold-Pressed'],
          operatingDays: ['Saturday', 'Sunday'],
          rating: 4.7,
          reviewCount: 16,
          coverImage: { url: 'https://images.unsplash.com/photo-1622597467836-f3285f2131b7?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 7,
        },
      },
      {
        user: {
          name: 'Hamza Qureshi',
          email: 'hamza.cheese@marketlink.org',
          phone: '+92 309 0123456',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Mountain Crest Artisan Cheeses',
          slug: 'mountain-crest-artisan-cheeses',
          contactPerson: 'Hamza Qureshi',
          phone: '+92 309 0123456',
          email: 'hamza.cheese@marketlink.org',
          address: 'Valley Dairy Farm, Abbottabad',
          stallNumber: 'Stall #09',
          description: 'Crafting European style organic goat and cow milk cheeses, aged gouda, feta, and fresh burrata.',
          specialties: ['Aged Gouda', 'Goat Milk Feta', 'Fresh Burrata', 'Cultured Cottage Cheese'],
          certifications: ['Artisan Dairy Guild', 'Pastured Milk'],
          operatingDays: ['Saturday', 'Sunday'],
          rating: 4.9,
          reviewCount: 31,
          coverImage: { url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 4,
        },
      },
      {
        user: {
          name: 'Haji Rafiq',
          email: 'rafiq.grains@marketlink.org',
          phone: '+92 310 1234567',
          password: 'password123',
          role: 'farmer',
          isVerified: true,
          profileImage: { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80' },
        },
        profile: {
          farmName: 'Golden Grain Organic Mills & Sourdough',
          slug: 'golden-grain-organic-mills-sourdough',
          contactPerson: 'Haji Rafiq',
          phone: '+92 310 1234567',
          email: 'rafiq.grains@marketlink.org',
          address: 'Heritage Mill, Sheikhupura Road',
          stallNumber: 'Stall #03',
          description: 'Traditional stone-ground whole wheat, heirloom barley, cold-fermented country sourdough loaves.',
          specialties: ['Country Sourdough Bread', 'Stone-Ground Whole Wheat', 'Rolled Oats', 'Multigrain Loaf'],
          certifications: ['Traditional Stone Ground', 'No Additives'],
          operatingDays: ['Friday', 'Saturday', 'Sunday'],
          rating: 4.8,
          reviewCount: 29,
          coverImage: { url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&auto=format&fit=crop&q=80' },
          profileImage: { url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=300&auto=format&fit=crop&q=80' },
          marketIndex: 6,
        },
      },
    ];

    const savedFarmerProfiles = [];
    for (const item of farmersSeed) {
      let u = await User.findOne({ email: item.user.email });
      if (!u) {
        u = await User.create(item.user);
      } else {
        u.role = 'farmer';
        u.isVerified = true;
        await u.save();
      }

      const assignedMarket = savedMarkets[item.profile.marketIndex % savedMarkets.length];
      let p = await FarmerProfile.findOne({ user: u._id });
      const profileData = {
        ...item.profile,
        user: u._id,
        market: assignedMarket._id,
        pickupWindows: [
          { day: 'Saturday', startTime: '09:00 AM', endTime: '01:00 PM', cutoffHours: 2, maxOrders: 35 },
          { day: 'Sunday', startTime: '09:00 AM', endTime: '01:00 PM', cutoffHours: 2, maxOrders: 35 }
        ],
        location: assignedMarket.location,
        isActive: true,
        isVerifiedFarmer: true,
      };

      if (!p) {
        p = await FarmerProfile.create(profileData);
      } else {
        Object.assign(p, profileData);
        await p.save();
      }
      savedFarmerProfiles.push(p);
    }
    console.log(`✅ Seeded ${savedFarmerProfiles.length} Farmer Profiles.`);

    // ── 4. SEED PRODUCTS (EXACTLY 5 PRODUCTS PER CATEGORY = 60 PRODUCTS) ──
    const productsData = [
      // 🥦 Category 1: Fresh Vegetables
      {
        name: 'Heirloom Vine-Ripened Red Tomatoes',
        slug: 'heirloom-vine-ripened-red-tomatoes',
        description: 'Naturally sweet, juicy, sun-ripened organic tomatoes harvested at peak flavor on Friday morning.',
        price: 180,
        unit: 'kg',
        stock: 65,
        weeklyStock: 70,
        harvestDay: 'Friday Morning Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'fresh-vegetables',
        farmerIndex: 0,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['tomatoes', 'organic', 'vegetables', 'heirloom'],
        rating: 4.9,
        reviewCount: 18,
      },
      {
        name: 'Farm Fresh Organic Baby Spinach',
        slug: 'farm-fresh-organic-baby-spinach',
        description: 'Tender, iron-rich baby spinach leaves, washed in natural spring water, ready for salads and cooking.',
        price: 120,
        unit: 'bunch',
        stock: 45,
        weeklyStock: 50,
        harvestDay: 'Saturday Dawn Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'fresh-vegetables',
        farmerIndex: 0,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['spinach', 'greens', 'leafy', 'organic'],
        rating: 4.8,
        reviewCount: 14,
      },
      {
        name: 'Organic Crisp Persian Cucumbers',
        slug: 'organic-crisp-persian-cucumbers',
        description: 'Thin-skinned, seedless crunchy cucumbers grown under natural sunlight with organic compost.',
        price: 140,
        unit: 'kg',
        stock: 55,
        weeklyStock: 60,
        harvestDay: 'Friday Morning Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'fresh-vegetables',
        farmerIndex: 0,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['cucumbers', 'vegetables', 'organic', 'salad'],
        rating: 4.8,
        reviewCount: 11,
      },
      {
        name: 'Farm Fresh Organic Sweet Corn',
        slug: 'farm-fresh-organic-sweet-corn',
        description: 'Tender golden kernels brimming with natural sweetness. Best steamed or grilled over hot coals.',
        price: 160,
        unit: 'kg',
        stock: 50,
        weeklyStock: 50,
        harvestDay: 'Friday Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'fresh-vegetables',
        farmerIndex: 0,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['sweet corn', 'corn', 'organic', 'vegetables'],
        rating: 4.8,
        reviewCount: 10,
      },
      {
        name: 'Organic Trio Bell Peppers (Red, Yellow, Green)',
        slug: 'organic-trio-bell-peppers',
        description: 'Vibrant crunchy sweet bell peppers rich in vitamin C and antioxidants. Grown in shade-net organic tunnels.',
        price: 240,
        unit: 'kg',
        stock: 40,
        weeklyStock: 45,
        harvestDay: 'Thursday Afternoon Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'fresh-vegetables',
        farmerIndex: 0,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['peppers', 'capsicum', 'organic', 'vegetables'],
        rating: 4.9,
        reviewCount: 16,
      },

      // 🍎 Category 2: Organic Fruits
      {
        name: 'Crisp Mountain Gala Apples',
        slug: 'crisp-mountain-gala-apples',
        description: 'Hand-picked from Swat high-altitude orchards, wonderfully sweet with a refreshing juicy crunch.',
        price: 280,
        unit: 'kg',
        stock: 80,
        weeklyStock: 90,
        harvestDay: 'Thursday Orchard Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'organic-fruits',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['apples', 'fruits', 'mountain', 'swat'],
        rating: 5.0,
        reviewCount: 22,
      },
      {
        name: 'Fresh Sun-Ripened Organic Strawberries',
        slug: 'fresh-sun-ripened-organic-strawberries',
        description: 'Fragrant, vibrant red strawberries picked fresh from organic berry beds. Perfect for snacking and desserts.',
        price: 420,
        unit: 'box',
        stock: 35,
        weeklyStock: 40,
        harvestDay: 'Friday Morning Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'organic-fruits',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['strawberries', 'berries', 'organic', 'fruits'],
        rating: 4.9,
        reviewCount: 20,
      },
      {
        name: 'Golden Sweet Sindhri & Chaunsa Mangoes',
        slug: 'golden-sweet-sindhri-chaunsa-mangoes',
        description: 'Tree-ripened organic mangoes from ancestral groves with intoxicating aroma and velvet honeyed pulp.',
        price: 360,
        unit: 'kg',
        stock: 70,
        weeklyStock: 80,
        harvestDay: 'Morning Tree Picking',
        images: [{ url: 'https://images.unsplash.com/photo-1553279768-865429fa0078?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'organic-fruits',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['mango', 'chaunsa', 'sindhri', 'fruits'],
        rating: 5.0,
        reviewCount: 35,
      },
      {
        name: 'Ruby Red Mountain Pomegranates (Kandahari)',
        slug: 'ruby-red-mountain-pomegranates',
        description: 'Large juicy sweet-tart ruby seeds with soft edible arils. Hand-sorted from valley orchards.',
        price: 320,
        unit: 'kg',
        stock: 45,
        weeklyStock: 50,
        harvestDay: 'Wednesday Orchard Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'organic-fruits',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['pomegranate', 'anar', 'fruits', 'organic'],
        rating: 4.8,
        reviewCount: 15,
      },
      {
        name: 'Fresh Farm Oranges & Mandarins (Kinnow)',
        slug: 'fresh-farm-oranges-mandarins-kinnow',
        description: 'Bursting with sweet tangy citrus juice, vitamin C, and easy-to-peel aromatic skin.',
        price: 220,
        unit: 'dozen',
        stock: 60,
        weeklyStock: 65,
        harvestDay: 'Daily Grove Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'organic-fruits',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['oranges', 'kinnow', 'citrus', 'fruits'],
        rating: 4.7,
        reviewCount: 19,
      },

      // 🥚 Category 3: Dairy & Farm Eggs
      {
        name: 'Pasture-Raised Free-Range Eggs',
        slug: 'pasture-raised-free-range-eggs',
        description: 'Golden rich yolks from hens roaming open grassy pastures with zero antibiotics or artificial feed.',
        price: 380,
        unit: 'dozen',
        stock: 50,
        weeklyStock: 60,
        harvestDay: 'Daily Morning Collection',
        images: [{ url: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'dairy-eggs',
        farmerIndex: 2,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['eggs', 'dairy', 'free-range', 'pastured'],
        rating: 5.0,
        reviewCount: 30,
      },
      {
        name: 'Grass-Fed Pure Raw Whole Milk',
        slug: 'grass-fed-pure-raw-whole-milk',
        description: 'Chilled unadulterated farm fresh milk with full natural cream, bottled in glass containers.',
        price: 250,
        unit: 'litre',
        stock: 40,
        weeklyStock: 40,
        harvestDay: 'Morning Milking',
        images: [{ url: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'dairy-eggs',
        farmerIndex: 2,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['milk', 'dairy', 'raw milk', 'organic'],
        rating: 4.9,
        reviewCount: 16,
      },
      {
        name: 'Artisan Farm-Churned Desi Ghee',
        slug: 'artisan-farm-churned-desi-ghee',
        description: 'Traditional slow-cooked golden clarified butter made from cultured grass-fed cow and buffalo cream.',
        price: 1850,
        unit: 'jar',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Traditional Woodfire Churned',
        images: [{ url: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'dairy-eggs',
        farmerIndex: 2,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['ghee', 'desi ghee', 'dairy', 'organic'],
        rating: 5.0,
        reviewCount: 28,
      },
      {
        name: 'Fresh Farm Cottage Paneer (Soft Block)',
        slug: 'fresh-farm-cottage-paneer',
        description: 'Creamy, melt-in-mouth cottage paneer pressed from whole farm fresh milk without any starch.',
        price: 480,
        unit: '500g',
        stock: 30,
        weeklyStock: 35,
        harvestDay: 'Friday Night Batch',
        images: [{ url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'dairy-eggs',
        farmerIndex: 2,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['paneer', 'cottage cheese', 'dairy', 'fresh'],
        rating: 4.8,
        reviewCount: 14,
      },
      {
        name: 'Probiotic Cultured Farm Yoghurt (Dahi)',
        slug: 'probiotic-cultured-farm-yoghurt',
        description: 'Thick, creamy set whole milk yoghurt made with traditional live heirloom cultures.',
        price: 220,
        unit: 'kg',
        stock: 35,
        weeklyStock: 40,
        harvestDay: 'Overnight Cultured',
        images: [{ url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'dairy-eggs',
        farmerIndex: 2,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['yoghurt', 'dahi', 'probiotic', 'dairy'],
        rating: 4.9,
        reviewCount: 12,
      },

      // 🍯 Category 4: Artisan Honey & Jams
      {
        name: 'Raw Margalla Wildflower Blossom Honey',
        slug: 'raw-margalla-wildflower-blossom-honey',
        description: '100% pure raw honey harvested from natural flora of Margalla hills. Unpasteurized and unfiltered.',
        price: 1350,
        unit: 'jar',
        stock: 30,
        weeklyStock: 35,
        harvestDay: 'Seasonal Extraction',
        images: [{ url: 'https://images.unsplash.com/photo-1471943311424-646960669fbc?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'honey-jams',
        farmerIndex: 3,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['honey', 'raw', 'wildflower', 'pure'],
        rating: 5.0,
        reviewCount: 26,
      },
      {
        name: 'Pure Cold-Extracted Sidr Berry Honey',
        slug: 'pure-cold-extracted-sidr-berry-honey',
        description: 'World-renowned mono-floral Sidr honey known for deep amber color, rich butterscotch notes and medicinal properties.',
        price: 1750,
        unit: 'jar',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Autumn Wild Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'honey-jams',
        farmerIndex: 3,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['sidr honey', 'honey', 'medicinal', 'raw'],
        rating: 5.0,
        reviewCount: 32,
      },
      {
        name: 'Handmade Organic Strawberry Jam (Low Sugar)',
        slug: 'handmade-organic-strawberry-jam',
        description: 'Cooked in small copper batches with whole orchard strawberries, organic raw cane sugar, and lemon juice.',
        price: 490,
        unit: 'jar',
        stock: 40,
        weeklyStock: 45,
        harvestDay: 'Artisan Kettle Cooked',
        images: [{ url: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'honey-jams',
        farmerIndex: 3,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['jam', 'strawberry jam', 'preserves', 'artisan'],
        rating: 4.8,
        reviewCount: 15,
      },
      {
        name: 'Wild Mountain Acacia Honey Comb Jar',
        slug: 'wild-mountain-acacia-honey-comb-jar',
        description: 'Crystal-clear light acacia honey containing a genuine slice of raw honeycomb straight from the hive.',
        price: 1550,
        unit: 'jar',
        stock: 20,
        weeklyStock: 25,
        harvestDay: 'Spring Hive Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1587049352851-8d4e89133924?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'honey-jams',
        farmerIndex: 3,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['honeycomb', 'acacia honey', 'honey', 'pure'],
        rating: 4.9,
        reviewCount: 17,
      },
      {
        name: 'Sun-Ripened Apricot & Orange Blossom Jam',
        slug: 'sun-ripened-apricot-orange-blossom-jam',
        description: 'Made from Hunza valley sun-dried apricots with subtle essence of fresh citrus blossoms.',
        price: 460,
        unit: 'jar',
        stock: 35,
        weeklyStock: 40,
        harvestDay: 'Batch Prepared',
        images: [{ url: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'honey-jams',
        farmerIndex: 3,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['apricot jam', 'jam', 'hunza', 'artisan'],
        rating: 4.8,
        reviewCount: 13,
      },

      // 🍞 Category 5: Bakery & Grains
      {
        name: 'Traditional Handcrafted Country Sourdough Loaf',
        slug: 'traditional-handcrafted-country-sourdough-loaf',
        description: '36-hour cold fermented sourdough bread baked with stone-ground flour and a caramelized crispy crust.',
        price: 450,
        unit: 'piece',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Fresh Baked Saturday Morning',
        images: [{ url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'bakery-grains',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['sourdough', 'bread', 'bakery', 'organic'],
        rating: 4.9,
        reviewCount: 17,
      },
      {
        name: 'Stone-Ground 100% Whole Wheat Chakki Atta',
        slug: 'stone-ground-whole-wheat-chakki-atta',
        description: 'Unbleached, pesticide-free wheat grains milled on traditional watermills with bran and germ intact.',
        price: 290,
        unit: '2kg',
        stock: 60,
        weeklyStock: 70,
        harvestDay: 'Freshly Milled Batch',
        images: [{ url: 'https://images.unsplash.com/photo-1608198093002-ad4e005484ec?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'bakery-grains',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['flour', 'atta', 'whole wheat', 'grains'],
        rating: 4.8,
        reviewCount: 21,
      },
      {
        name: 'Artisan Olive & Rosemary Focaccia Bread',
        slug: 'artisan-olive-rosemary-focaccia-bread',
        description: 'Extra virgin olive oil drenched airy Italian flatbread topped with kalamata olives, rosemary, and sea salt.',
        price: 390,
        unit: 'piece',
        stock: 20,
        weeklyStock: 25,
        harvestDay: 'Baked Saturday Morning',
        images: [{ url: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'bakery-grains',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['focaccia', 'bread', 'bakery', 'artisan'],
        rating: 4.9,
        reviewCount: 15,
      },
      {
        name: 'Organic Rolled Breakfast Oats',
        slug: 'organic-rolled-breakfast-oats',
        description: 'Wholesome thick-cut steamed oat flakes. High in beta-glucan fiber for energizing morning porridge.',
        price: 340,
        unit: '500g',
        stock: 45,
        weeklyStock: 50,
        harvestDay: 'Freshly Packaged',
        images: [{ url: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'bakery-grains',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['oats', 'porridge', 'breakfast', 'grains'],
        rating: 4.7,
        reviewCount: 11,
      },
      {
        name: 'Multigrain Seeded Sourdough Batard',
        slug: 'multigrain-seeded-sourdough-batard',
        description: 'Nutty sourdough loaf loaded with toasted pumpkin seeds, sunflower seeds, flaxseeds, and black sesame.',
        price: 490,
        unit: 'piece',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Fresh Baked Saturday Morning',
        images: [{ url: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'bakery-grains',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['multigrain', 'sourdough', 'bread', 'bakery'],
        rating: 5.0,
        reviewCount: 19,
      },

      // 🌿 Category 6: Fresh Herbs & Spices
      {
        name: 'Organic Sweet Italian Basil & Mint Bundle',
        slug: 'organic-sweet-italian-basil-mint-bundle',
        description: 'Intensely fragrant fresh herb bouquet harvested with roots intact for maximum freshness and flavor.',
        price: 110,
        unit: 'bunch',
        stock: 60,
        weeklyStock: 65,
        harvestDay: 'Friday Afternoon Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1628556270448-4d4e4148e1b1?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'herbs-spices',
        farmerIndex: 4,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['basil', 'mint', 'herbs', 'fresh'],
        rating: 4.8,
        reviewCount: 12,
      },
      {
        name: 'Fresh Rosemary, Thyme & Sage Bouquet',
        slug: 'fresh-rosemary-thyme-sage-bouquet',
        description: 'Woody aromatic culinary herbs perfect for roasts, soups, herbal teas, and artisan seasoning.',
        price: 150,
        unit: 'bunch',
        stock: 40,
        weeklyStock: 45,
        harvestDay: 'Friday Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'herbs-spices',
        farmerIndex: 4,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['rosemary', 'thyme', 'sage', 'herbs'],
        rating: 4.9,
        reviewCount: 16,
      },
      {
        name: 'Organic Whole Green Cardamom (Elaichi)',
        slug: 'organic-whole-green-cardamom',
        description: 'Jumbo aromatic green cardamom pods hand-harvested and sun-cured. Intense sweet aroma.',
        price: 580,
        unit: '100g',
        stock: 35,
        weeklyStock: 40,
        harvestDay: 'Sun Cured Spices',
        images: [{ url: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'herbs-spices',
        farmerIndex: 4,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['cardamom', 'elaichi', 'spices', 'organic'],
        rating: 5.0,
        reviewCount: 24,
      },
      {
        name: 'Pure Sun-Dried Organic Turmeric Powder',
        slug: 'pure-sun-dried-organic-turmeric-powder',
        description: 'High-curcumin organic turmeric roots stone-ground to a vibrant golden yellow powder with zero lead or additives.',
        price: 280,
        unit: '250g',
        stock: 50,
        weeklyStock: 55,
        harvestDay: 'Stone Ground Batch',
        images: [{ url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'herbs-spices',
        farmerIndex: 4,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['turmeric', 'haldi', 'curcumin', 'spices'],
        rating: 4.9,
        reviewCount: 18,
      },
      {
        name: 'Fresh Organic Coriander & Curly Parsley',
        slug: 'fresh-organic-coriander-curly-parsley',
        description: 'Crisp green fragrant coriander and curly parsley harvested with morning dew.',
        price: 90,
        unit: 'bunch',
        stock: 65,
        weeklyStock: 70,
        harvestDay: 'Saturday Dawn Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'herbs-spices',
        farmerIndex: 4,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['coriander', 'dhania', 'parsley', 'herbs'],
        rating: 4.7,
        reviewCount: 10,
      },

      // 🍹 Category 7: Cold-Pressed Juices
      {
        name: 'Raw Cold-Pressed Carrot-Orange Juice (500ml)',
        slug: 'raw-cold-pressed-carrot-orange-juice',
        description: 'Freshly extracted from organic farm carrots and sweet oranges. Zero water, sugar, or preservatives.',
        price: 360,
        unit: 'bottle',
        stock: 35,
        weeklyStock: 40,
        harvestDay: 'Freshly Pressed Saturday',
        images: [{ url: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'cold-pressed-juices',
        farmerIndex: 7,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['juice', 'cold-pressed', 'organic', 'fresh'],
        rating: 4.8,
        reviewCount: 14,
      },
      {
        name: 'Green Detox Super Cleanse (500ml)',
        slug: 'green-detox-super-cleanse',
        description: 'Nutrient-rich cold pressed blend of organic celery, green apple, cucumber, kale, ginger, and lime.',
        price: 420,
        unit: 'bottle',
        stock: 30,
        weeklyStock: 35,
        harvestDay: 'Freshly Pressed Saturday',
        images: [{ url: 'https://images.unsplash.com/photo-1610970881699-44a5587cabec?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'cold-pressed-juices',
        farmerIndex: 7,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['green juice', 'detox', 'cleanse', 'cold-pressed'],
        rating: 4.9,
        reviewCount: 19,
      },
      {
        name: 'Ruby Beetroot & Pomegranate Vitality Elixir (500ml)',
        slug: 'ruby-beetroot-pomegranate-vitality-elixir',
        description: 'Energizing blood-purifying tonic made from earthy beets, sweet pomegranates, and crisp red apples.',
        price: 390,
        unit: 'bottle',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Freshly Pressed Saturday',
        images: [{ url: 'https://images.unsplash.com/photo-1556761223-4c4282c73f77?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'cold-pressed-juices',
        farmerIndex: 7,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['beetroot', 'pomegranate', 'juice', 'vitality'],
        rating: 4.7,
        reviewCount: 11,
      },
      {
        name: 'Raw Immunity Ginger-Turmeric Fire Shot (100ml)',
        slug: 'raw-immunity-ginger-turmeric-fire-shot',
        description: 'Potent wellness shot with cold pressed wild ginger root, fresh turmeric, lemon, and a pinch of black pepper.',
        price: 220,
        unit: 'bottle',
        stock: 50,
        weeklyStock: 60,
        harvestDay: 'Freshly Pressed Saturday',
        images: [{ url: 'https://images.unsplash.com/photo-1546173159-315724a31696?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'cold-pressed-juices',
        farmerIndex: 7,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['wellness shot', 'ginger', 'immunity', 'juice'],
        rating: 5.0,
        reviewCount: 23,
      },
      {
        name: 'Fresh Cold-Pressed Sugarcane Juice with Mint (500ml)',
        slug: 'fresh-cold-pressed-sugarcane-juice-with-mint',
        description: 'Pure refreshing cane juice pressed with farm mint leaves, ginger and black salt.',
        price: 250,
        unit: 'bottle',
        stock: 40,
        weeklyStock: 45,
        harvestDay: 'Morning Extracted',
        images: [{ url: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'cold-pressed-juices',
        farmerIndex: 7,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['sugarcane', 'cane juice', 'fresh', 'mint'],
        rating: 4.8,
        reviewCount: 17,
      },

      // 🫙 Category 8: Farm Pantry & Preserves
      {
        name: 'Cold-Pressed Extra Virgin Mustard Oil',
        slug: 'cold-pressed-extra-virgin-mustard-oil',
        description: 'Traditional wood-pressed kachi ghani organic mustard oil, rich in omega-3 and pungent aroma.',
        price: 650,
        unit: 'bottle',
        stock: 30,
        weeklyStock: 35,
        harvestDay: 'Cold Wood-Pressed',
        images: [{ url: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'pantry-preserves',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['oil', 'mustard oil', 'cold-pressed', 'pantry'],
        rating: 4.9,
        reviewCount: 13,
      },
      {
        name: 'Grandmother\'s Organic Mixed Vegetable Achaar',
        slug: 'grandmothers-organic-mixed-vegetable-achaar',
        description: 'Sun-matured raw mango, carrot, cauliflower, and green chili pickle in pure mustard oil and whole spices.',
        price: 420,
        unit: 'jar',
        stock: 35,
        weeklyStock: 40,
        harvestDay: 'Sun Matured Batch',
        images: [{ url: 'https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'pantry-preserves',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['pickle', 'achaar', 'organic', 'pantry'],
        rating: 5.0,
        reviewCount: 25,
      },
      {
        name: 'Sun-Dried Whole Kashmiri Red Chillies',
        slug: 'sun-dried-whole-kashmiri-red-chillies',
        description: 'Naturally dried vibrant red whole chillies known for mild heat and rich deep natural red color.',
        price: 260,
        unit: '200g',
        stock: 45,
        weeklyStock: 50,
        harvestDay: 'Sun Dried Produce',
        images: [{ url: 'https://images.unsplash.com/photo-1583119022894-919a68a3d0e3?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'pantry-preserves',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['chillies', 'kashmiri mirch', 'spices', 'pantry'],
        rating: 4.8,
        reviewCount: 14,
      },
      {
        name: 'Raw Unfiltered Apple Cider Vinegar with Mother',
        slug: 'raw-unfiltered-apple-cider-vinegar-with-mother',
        description: 'Naturally fermented from organic Swat mountain apples. Packed with beneficial gut probiotics and live enzymes.',
        price: 690,
        unit: 'bottle',
        stock: 30,
        weeklyStock: 35,
        harvestDay: 'Oak Barrel Aged',
        images: [{ url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'pantry-preserves',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['acv', 'apple cider vinegar', 'probiotic', 'pantry'],
        rating: 4.9,
        reviewCount: 22,
      },
      {
        name: 'Sun-Dried Tomatoes in Cold-Pressed Olive Oil',
        slug: 'sun-dried-tomatoes-in-cold-pressed-olive-oil',
        description: 'Sweet, chewy sun-dried heirloom tomato petals infused with garlic, oregano, and virgin olive oil.',
        price: 540,
        unit: 'jar',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Hand Preserved',
        images: [{ url: 'https://images.unsplash.com/photo-1601648764658-cf37e8c89b70?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'pantry-preserves',
        farmerIndex: 9,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['sun dried tomatoes', 'preserves', 'artisan', 'pantry'],
        rating: 4.8,
        reviewCount: 16,
      },

      // 🍄 Category 9: Gourmet Mushrooms
      {
        name: 'Fresh Pearl Oyster & Shiitake Mushrooms',
        slug: 'fresh-pearl-oyster-shiitake-mushrooms',
        description: 'Velvety, rich umami flavor oyster mushrooms grown organically on sterilized hardwood sawdust.',
        price: 550,
        unit: '500g',
        stock: 30,
        weeklyStock: 35,
        harvestDay: 'Friday Night Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1611944212129-29977ae1398c?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'gourmet-mushrooms',
        farmerIndex: 5,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['mushrooms', 'oyster', 'gourmet', 'organic'],
        rating: 4.9,
        reviewCount: 15,
      },
      {
        name: 'Gourmet King Trumpet Mushroom Stems',
        slug: 'gourmet-king-trumpet-mushroom-stems',
        description: 'Thick, meaty stems that sear beautifully like scallops. Exceptional savory flavor and texture.',
        price: 640,
        unit: '400g',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Friday Night Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1508747703725-719777637510?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'gourmet-mushrooms',
        farmerIndex: 5,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['king trumpet', 'mushrooms', 'gourmet', 'culinary'],
        rating: 5.0,
        reviewCount: 18,
      },
      {
        name: 'Organic Lion\'s Mane Nootropic Mushrooms',
        slug: 'organic-lions-mane-nootropic-mushrooms',
        description: 'Exotic cascading white mushroom known for cognitive support, brain health, and delicate lobster-like flavor.',
        price: 780,
        unit: '300g',
        stock: 20,
        weeklyStock: 25,
        harvestDay: 'Saturday Dawn Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'gourmet-mushrooms',
        farmerIndex: 5,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['lions mane', 'medicinal', 'mushrooms', 'organic'],
        rating: 4.9,
        reviewCount: 12,
      },
      {
        name: 'Fresh Organic White Button Mushrooms',
        slug: 'fresh-organic-white-button-mushrooms',
        description: 'Firm, clean white button mushrooms freshly harvested from temperature controlled organic darkrooms.',
        price: 340,
        unit: '400g',
        stock: 45,
        weeklyStock: 50,
        harvestDay: 'Daily Morning Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'gourmet-mushrooms',
        farmerIndex: 5,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['button mushrooms', 'mushrooms', 'fresh', 'vegetables'],
        rating: 4.7,
        reviewCount: 14,
      },
      {
        name: 'Sun-Dried Wild Forest Porcini & Morels Mix',
        slug: 'sun-dried-wild-forest-porcini-morels-mix',
        description: 'Hand-foraged Himalayan wild morels and porcini slices. Rehydrates into intensely rich mushroom broth.',
        price: 920,
        unit: '150g',
        stock: 15,
        weeklyStock: 20,
        harvestDay: 'Wild Foraged',
        images: [{ url: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'gourmet-mushrooms',
        farmerIndex: 5,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['morels', 'porcini', 'wild mushrooms', 'dried'],
        rating: 5.0,
        reviewCount: 20,
      },

      // 🌱 Category 10: Microgreens & Sprouts
      {
        name: 'Live Broccoli & Radish Microgreens Clamshell',
        slug: 'live-broccoli-radish-microgreens-clamshell',
        description: 'Living superfood greens with spicy kick, packed with sulforaphane, vitamin C, and antioxidants.',
        price: 260,
        unit: 'pack',
        stock: 40,
        weeklyStock: 45,
        harvestDay: 'Saturday Morning Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'microgreens-sprouts',
        farmerIndex: 6,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['microgreens', 'sprouts', 'superfood', 'healthy'],
        rating: 5.0,
        reviewCount: 18,
      },
      {
        name: 'Live Nutrient-Dense Sunflower Sprouts',
        slug: 'live-nutrient-dense-sunflower-sprouts',
        description: 'Crispy nutty sunflower greens with thick tender stems and rich chlorophyll content.',
        price: 240,
        unit: 'pack',
        stock: 35,
        weeklyStock: 40,
        harvestDay: 'Saturday Morning Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'microgreens-sprouts',
        farmerIndex: 6,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['sunflower sprouts', 'microgreens', 'living greens', 'raw'],
        rating: 4.9,
        reviewCount: 15,
      },
      {
        name: 'Sweet Crunchy Pea Tendril Shoots',
        slug: 'sweet-crunchy-pea-tendril-shoots',
        description: 'Tender curly pea shoots brimming with sweet spring pea flavor. Perfect garnish for salads and pasta.',
        price: 250,
        unit: 'pack',
        stock: 30,
        weeklyStock: 35,
        harvestDay: 'Saturday Morning Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'microgreens-sprouts',
        farmerIndex: 6,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['pea shoots', 'microgreens', 'fresh', 'sprouts'],
        rating: 4.8,
        reviewCount: 12,
      },
      {
        name: 'Organic Wheatgrass Living Soil Tray',
        slug: 'organic-wheatgrass-living-soil-tray',
        description: 'Whole live tray of fresh wheatgrass ready for daily morning juicing. Packed with amino acids.',
        price: 380,
        unit: 'tray',
        stock: 20,
        weeklyStock: 25,
        harvestDay: 'Live Tray Delivery',
        images: [{ url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'microgreens-sprouts',
        farmerIndex: 6,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['wheatgrass', 'live tray', 'superfood', 'juicing'],
        rating: 4.9,
        reviewCount: 17,
      },
      {
        name: 'Gourmet Rainbow Salad Microgreens Blend',
        slug: 'gourmet-rainbow-salad-microgreens-blend',
        description: 'Colorful vibrant mix of red amaranth, purple kohlrabi, spicy arugula, and golden alfalfa sprouts.',
        price: 290,
        unit: 'pack',
        stock: 35,
        weeklyStock: 40,
        harvestDay: 'Saturday Dawn Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'microgreens-sprouts',
        farmerIndex: 6,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['rainbow mix', 'microgreens', 'salad blend', 'organic'],
        rating: 5.0,
        reviewCount: 21,
      },

      // 🌰 Category 11: Raw Nuts & Seeds
      {
        name: 'Raw Himalayan Wild Mountain Walnuts (Akhrot)',
        slug: 'raw-himalayan-wild-mountain-walnuts',
        description: 'Paper-shelled rich organic walnut halves harvested from high valleys. High in brain-healthy omega-3s.',
        price: 780,
        unit: '250g',
        stock: 40,
        weeklyStock: 45,
        harvestDay: 'Sun Cured Batch',
        images: [{ url: 'https://images.unsplash.com/photo-1549590143-d5855148a9d5?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'nuts-seeds',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['walnuts', 'akhrot', 'nuts', 'organic'],
        rating: 5.0,
        reviewCount: 27,
      },
      {
        name: 'Sun-Dried Mountain Sweet Almonds (Badam Gari)',
        slug: 'sun-dried-mountain-sweet-almonds',
        description: 'Unprocessed natural organic almonds with sweet milky flavor. Packed with vitamin E and protein.',
        price: 720,
        unit: '250g',
        stock: 45,
        weeklyStock: 50,
        harvestDay: 'Valley Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1571680322279-a226e6a4cc2a?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'nuts-seeds',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['almonds', 'badam', 'nuts', 'superfood'],
        rating: 4.9,
        reviewCount: 23,
      },
      {
        name: 'Organic Raw Green Pumpkin Seeds (Pepitas)',
        slug: 'organic-raw-green-pumpkin-seeds',
        description: 'Zinc-rich crunchy raw pumpkin seeds. Great for snacking, tossing in salads, or smoothie bowls.',
        price: 390,
        unit: '250g',
        stock: 50,
        weeklyStock: 55,
        harvestDay: 'Freshly Packed',
        images: [{ url: 'https://images.unsplash.com/photo-1590779033100-9f60a05a013d?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'nuts-seeds',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['pumpkin seeds', 'pepitas', 'seeds', 'organic'],
        rating: 4.8,
        reviewCount: 16,
      },
      {
        name: 'Pure Black & White Organic Chia Seeds',
        slug: 'pure-black-white-organic-chia-seeds',
        description: 'Superfood chia seeds with exceptional soluble fiber and hydration properties. Perfect for puddings.',
        price: 430,
        unit: '250g',
        stock: 40,
        weeklyStock: 45,
        harvestDay: 'Cleaned & Sorted',
        images: [{ url: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'nuts-seeds',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['chia seeds', 'superfood', 'seeds', 'organic'],
        rating: 4.9,
        reviewCount: 19,
      },
      {
        name: 'Premium Wild Roasted Pine Nuts (Chilgoza)',
        slug: 'premium-wild-roasted-pine-nuts-chilgoza',
        description: 'Handpicked wild pine nuts from Sulaiman range forests. Rich buttery crunch and delicate aroma.',
        price: 1550,
        unit: '150g',
        stock: 20,
        weeklyStock: 25,
        harvestDay: 'Forest Harvest',
        images: [{ url: 'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'nuts-seeds',
        farmerIndex: 1,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['chilgoza', 'pine nuts', 'nuts', 'wild'],
        rating: 5.0,
        reviewCount: 31,
      },

      // 🧀 Category 12: Artisan Cheeses
      {
        name: 'Aged Mountain Goat Milk Feta Cheese',
        slug: 'aged-mountain-goat-milk-feta-cheese',
        description: 'Brined artisanal feta cheese with tangy creamy notes, made from pastured mountain goat milk.',
        price: 780,
        unit: '250g',
        stock: 20,
        weeklyStock: 25,
        harvestDay: 'Artisan Cellar Cured',
        images: [{ url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'artisan-cheeses',
        farmerIndex: 8,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['cheese', 'feta', 'goat milk', 'artisan'],
        rating: 5.0,
        reviewCount: 21,
      },
      {
        name: 'Fresh Farm Creamy Burrata Cheese Ball',
        slug: 'fresh-farm-creamy-burrata-cheese-ball',
        description: 'Handmade mozzarella pouch filled with rich stracciatella cream. Best served with tomatoes and olive oil.',
        price: 680,
        unit: 'piece',
        stock: 20,
        weeklyStock: 25,
        harvestDay: 'Friday Night Crafted',
        images: [{ url: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'artisan-cheeses',
        farmerIndex: 8,
        isOrganic: true,
        isAvailable: true,
        isFeatured: true,
        tags: ['burrata', 'cheese', 'artisan', 'fresh'],
        rating: 5.0,
        reviewCount: 26,
      },
      {
        name: 'Artisan Smoked Gouda Cheese Wedge',
        slug: 'artisan-smoked-gouda-cheese-wedge',
        description: 'Naturally smoked over applewood chips with nutty, buttery undertones and smooth texture.',
        price: 890,
        unit: '300g',
        stock: 18,
        weeklyStock: 20,
        harvestDay: '60-Day Cellar Aged',
        images: [{ url: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'artisan-cheeses',
        farmerIndex: 8,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['gouda', 'smoked cheese', 'cheese', 'artisan'],
        rating: 4.9,
        reviewCount: 18,
      },
      {
        name: 'Traditional Cultured Halloumi Grilling Cheese',
        slug: 'traditional-cultured-halloumi-grilling-cheese',
        description: 'Semi-hard cheese with high melting point. Sears to golden perfection on a skillet or barbecue grill.',
        price: 640,
        unit: '250g',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Crafted Batch',
        images: [{ url: 'https://images.unsplash.com/photo-1626957341926-98752fc2ba90?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'artisan-cheeses',
        farmerIndex: 8,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['halloumi', 'grilling cheese', 'cheese', 'artisan'],
        rating: 4.8,
        reviewCount: 14,
      },
      {
        name: 'Handcrafted Sweet Whey Ricotta Cheese',
        slug: 'handcrafted-sweet-whey-ricotta-cheese',
        description: 'Delicate, fluffy fresh ricotta made from sweet whey of farm fresh milk. Ideal for pastas and desserts.',
        price: 460,
        unit: '300g',
        stock: 25,
        weeklyStock: 30,
        harvestDay: 'Friday Night Crafted',
        images: [{ url: 'https://images.unsplash.com/photo-1559561853-08451507cbe7?w=600&auto=format&fit=crop&q=80' }],
        categorySlug: 'artisan-cheeses',
        farmerIndex: 8,
        isOrganic: true,
        isAvailable: true,
        isFeatured: false,
        tags: ['ricotta', 'cheese', 'dairy', 'fresh'],
        rating: 4.8,
        reviewCount: 12,
      },
    ];

    const savedProducts = [];
    for (const prod of productsData) {
      const cat = savedCategories.find(c => c.slug === prod.categorySlug) || savedCategories[0];
      const farmer = savedFarmerProfiles[prod.farmerIndex % savedFarmerProfiles.length];

      let p = await Product.findOne({ $or: [{ slug: prod.slug }, { name: prod.name }] });
      const pData = {
        ...prod,
        category: cat._id,
        farmer: farmer._id,
        market: farmer.market,
      };

      if (!p) {
        p = await Product.create(pData);
      } else {
        Object.assign(p, pData);
        await p.save();
      }
      savedProducts.push(p);
    }
    console.log(`✅ Seeded ${savedProducts.length} Produce Products (5 per category).`);

    // ── 5. SEED STOREFRONT BANNERS (4 Banners) ──
    const bannersData = [
      {
        title: 'Spring Organic Harvest Festival',
        subtitle: 'Pre-Order 100% Certified Farm-Fresh Produce',
        description: 'Connecting you with verified local growers for convenient Saturday & Sunday farmers market pickups.',
        image: { url: '/dan-meyers-IQVFVH0ajag-unsplash.jpg' },
        link: '/products',
        category: 'main',
        position: 1,
        isActive: true,
      },
      {
        title: 'Heirloom Fruits & Berries',
        subtitle: 'Direct from Swat Mountain Orchards',
        description: 'Sweet Gala apples, freshly harvested organic strawberries, and sun-ripened pomegranates.',
        image: { url: '/land-o-lakes-inc-DdcWKBbJeEI-unsplash.jpg' },
        link: '/products?category=organic-fruits',
        category: 'main',
        position: 2,
        isActive: true,
      },
      {
        title: 'Raw Wildflower Honey & Artisan Dairy',
        subtitle: 'Pure, Unfiltered & Pasture-Raised',
        description: 'Cold-extracted Sidr honey, free-range eggs, farm churned butter and artisan cheeses.',
        image: { url: '/reba-spike-elcVuEs24Bc-unsplash.jpg' },
        link: '/products?category=honey-jams',
        category: 'main',
        position: 3,
        isActive: true,
      },
      {
        title: 'Meet Your Local Organic Growers',
        subtitle: 'Transparency From Soil to Basket',
        description: 'Know exactly who nurtures your food and support sustainable family agriculture in your community.',
        image: { url: '/zoe-richardson-D_VjFp1ds1Y-unsplash.jpg' },
        link: '/farmers',
        category: 'promo',
        position: 4,
        isActive: true,
      },
    ];

    for (const b of bannersData) {
      let existing = await Banner.findOne({ title: b.title });
      if (!existing) {
        await Banner.create(b);
      } else {
        Object.assign(existing, b);
        await existing.save();
      }
    }
    console.log(`✅ Seeded ${bannersData.length} Storefront Banners.`);

    // ── 6. SEED VERIFIED CUSTOMER REVIEWS (10 Reviews) ──
    let customerUser = await User.findOne({ email: 'customer.demo@marketlink.org' });
    if (!customerUser) {
      customerUser = await User.create({
        name: 'Saad Farooqui',
        email: 'customer.demo@marketlink.org',
        password: 'password123',
        phone: '+92 300 9876543',
        role: 'user',
        isVerified: true,
        profileImage: { url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&auto=format&fit=crop&q=80' },
      });
    }

    const reviewsData = [
      {
        comment: 'The heirloom tomatoes are incredibly sweet and flavorful! Nothing like supermarket produce. Picked up on Saturday morning perfectly fresh.',
        rating: 5,
        productIndex: 0,
        farmerIndex: 0,
        reply: 'Thank you Saad! We harvest them just a few hours before market opening so you get the best sweetness!',
      },
      {
        comment: 'The gala apples from Swat orchards are crisp, fragrant, and so juicy. Highly recommend pre-ordering to ensure stock!',
        rating: 5,
        productIndex: 5,
        farmerIndex: 1,
        reply: 'Appreciate your love for our high-altitude orchard harvest! Glad you enjoyed them.',
      },
      {
        comment: 'These pastured free-range eggs have rich deep orange yolks. Outstanding quality and taste for breakfast.',
        rating: 5,
        productIndex: 10,
        farmerIndex: 2,
        reply: 'Our hens live happily on green grass all day. Thank you for supporting our ethical farm!',
      },
      {
        comment: 'Pure Sidr honey with authentic floral aroma. You can taste the enzymes and pure purity in every spoonful.',
        rating: 5,
        productIndex: 15,
        farmerIndex: 3,
        reply: 'Honored by your review! We ensure zero heating or artificial processing.',
      },
      {
        comment: 'The country sourdough bread has the best crust and texture. Lasted the whole week without losing softness.',
        rating: 5,
        productIndex: 20,
        farmerIndex: 9,
        reply: 'Baked fresh every weekend at 5 AM! Thanks for the wonderful feedback.',
      },
      {
        comment: 'Fresh rosemary and thyme made an incredible marinade. Super aromatic and fresh.',
        rating: 5,
        productIndex: 25,
        farmerIndex: 4,
        reply: 'Thank you! We cultivate them under strictly controlled organic moisture.',
      },
      {
        comment: 'The cold-pressed carrot orange juice was so refreshing and naturally sweet. My kids loved it!',
        rating: 5,
        productIndex: 30,
        farmerIndex: 7,
        reply: 'Delighted to hear! 100% farm fruit with no water or sugar added.',
      },
      {
        comment: 'The homemade mixed vegetable pickle brings back childhood flavors. Authentic mustard oil and spice blend.',
        rating: 5,
        productIndex: 35,
        farmerIndex: 9,
        reply: 'Thank you! We sun-mature it for 3 weeks in glass jars.',
      },
      {
        comment: 'The mountain goat feta cheese has authentic Mediterranean creaminess and depth. Excellent artisan craft.',
        rating: 5,
        productIndex: 55,
        farmerIndex: 8,
        reply: 'Aged in natural wooden barrels for 60 days. Thank you for appreciating artisan cheese!',
      },
      {
        comment: 'Super fresh strawberries and microgreens. The packaging in biodegradable boxes was also very impressive.',
        rating: 5,
        productIndex: 6,
        farmerIndex: 1,
        reply: 'We are committed to both organic produce and eco-friendly packaging!',
      },
    ];

    for (const rev of reviewsData) {
      const prod = savedProducts[rev.productIndex % savedProducts.length];
      const farmer = savedFarmerProfiles[rev.farmerIndex % savedFarmerProfiles.length];

      let existing = await Review.findOne({ customer: customerUser._id, product: prod._id });
      if (!existing) {
        await Review.create({
          customer: customerUser._id,
          product: prod._id,
          farmer: farmer._id,
          rating: rev.rating,
          comment: rev.comment,
          isApproved: true,
          reply: {
            comment: rev.reply,
            repliedAt: new Date(),
          },
        });
      }
    }
    console.log(`✅ Seeded ${reviewsData.length} Customer Reviews.`);

    console.log('🎉 ALL DATABASE SEEDING COMPLETED SUCCESSFULLY! 60 PRODUCTS (5 PER CATEGORY) READY.');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error during database seeding:', error);
    process.exit(1);
  }
};

seedDatabase();
